# Travis CI for building ArgumentReader
# -------------------------------------

language: csharp
solution: ArgumentsExtended.sln
mono: none
dotnet: 3.1.301

addons:
 apt:
   packages:
     - zip

install:
  - dotnet restore

script:
  - dotnet test
  - dotnet pack ./ArgumentsLib/*.csproj -c Release
  - ls -l ./ArgumentsLib/bin/Debug
  - ls -l ./ArgumentsLib/bin/Release

before_deploy:
  - dotnet build -c Release -o ./output
  - find ./output -name "*Lib.dll" -maxdepth 1 | zip -@ ArgumentReader.zip
  - dotnet nuget push ./output/*.nupkg -k $NUGET_TOKEN -s "https://api.nuget.org/v3/index.json" 
    
deploy:
  provider: releases
  overwrite: true
  api_key: $GITHUB_TOKEN
  file:
    - "./ArgumentReader.zip"
    - "./output/ArgumentMarshalerLib.dll"
    - "./output/ArgumentsLib.dll"
    - "./output/BooleanMarshalerLib.dll"
    - "./output/IntegerMarshalerLib.dll"
    - "./output/StringMarshalerLib.dll"
  skip_cleanup: true
  keep_history: true
  on:
    - tags: true
